print("Họ và Tên của anh Hùng: ")
Ten = input()
print("Tuổi của anh Hùng: ")
Tuoi = input(int)
print("Giới tính: ")
GT = input()
print("Tình Trạng hôn nhân: ")
TT = input()
print("Họ và Tên của anh Hùng: " + Ten)
print("Tuổi của anh Hùng: " + Tuoi)
print("Giới tính: " + GT)
print("Tình Trạng hôn nhân: " + TT)
